apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: app-frontend
    newName: 192.168.178.183:5010/app-frontend
    newTag: dev
  - name: hauswerk-firmware
    newName: 192.168.178.183:5010/hauswerk-firmware
    newTag: dev
  - name: esp32-flasher
    newName: 192.168.178.183:5010/esp32-flasher
    newTag: latest
patches:
  - target:
      kind: Deployment
      name: mosquitto
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: ENV
            value: "dev"
  - target:
      kind: Deployment
      name: frontend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Job
      name: esp32-firmware-flasher
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "Hauswasserwerk.local"
